# Generated by Django 4.2.16 on 2024-09-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='sender',
            field=models.CharField(default='sender', max_length=20),
        ),
    ]
