# Generated by Django 4.2.16 on 2024-09-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_friendlist_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='sender',
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='sender', max_length=20)),
                ('receiver', models.CharField(default='receiver', max_length=20)),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new.customer')),
            ],
        ),
    ]
