# Generated by Django 4.2.16 on 2024-09-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_remove_friendlist_sender_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapping',
            old_name='receiver',
            new_name='rec',
        ),
    ]
